# Docker Compose for validating Doppler integration
version: '3.8'

services:
  rwwwrse-doppler-test:
    image: ghcr.io/albedosehen/rwwwrse:latest
    container_name: rwwwrse-doppler-test
    ports:
      - "8080:8080"
    environment:
      # Doppler authentication
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
      DOPPLER_PROJECT: ${DOPPLER_PROJECT:-rwwwrse}
      DOPPLER_CONFIG: ${DOPPLER_CONFIG:-dev}
      
      # Basic configuration (may be overridden by Doppler)
      RWWWRSE_LOG_LEVEL: debug
      RWWWRSE_PORT: 8080
      
      # Test-specific configuration
      RWWWRSE_SERVER_HOST: "0.0.0.0"
      RWWWRSE_METRICS_ENABLED: "true"
      RWWWRSE_METRICS_PATH: "/metrics"
      
      # Route configuration for test
      RWWWRSE_ROUTES_TEST_HOST: "localhost"
      RWWWRSE_ROUTES_TEST_TARGET: "http://echo-server:8080"
    networks:
      - doppler-test
    restart: "no"
    command: ["/bin/sh", "-c", "echo 'Testing Doppler integration...' && sleep 5 && env | grep RWWWRSE_ && /app/rwwwrse"]
    volumes:
      - ./logs:/app/logs
    depends_on:
      - echo-server

  # Simple echo server to test connectivity
  echo-server:
    image: ealen/echo-server:latest
    container_name: echo-server
    environment:
      - PORT=8080
    networks:
      - doppler-test

networks:
  doppler-test:
    driver: bridge